### ISSUE TITLE
Also support orientationchange

### ISSUE THREAD

**Issue by DanielRuf** [mandymichael/fluid-axis-variation-events#1]
The code should be applied on `resize` and `orientationchange` (example in readme).

**Comment by mandymichael** [comment]
Are you suggesting there should be other examples in the readme of how you can use the code?

The function can be passed into any event that you want, it's not specific to resize, it can be used for scroll events, sensor apis, mouse position. It really does not matter.

**Comment by DanielRuf** [comment]
Basically the example is incomplete as both events should trigger that. If I find the time I will provide a PR.
